version: '3'
services:
  webapp:
    build: ./
    depends_on:
      - database
    command: ['gunicorn', '--workers=1', '--threads=4', 'habits.app:create_app()', '--bind', '0.0.0.0:8000', '--reload']
    ports:
      - "3000:8000"
    environment:
      - PYTHONUNBUFFERED=1  # Necessary to flush stdout immediately instead of buffering it for docker compose
    volumes:
      - ./:/app/habits/habits
  database:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=habits
      - POSTGRES_USER=habits
      - POSTGRES_DB=habits
    volumes:
      - database:/var/lib/postgresql/data


volumes:
  database: